apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: converter-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: converter
  updatePolicy:
    updateMode: "Auto"  # Automatically adjusts resources
